### ISSUE TITLE
Massive Memory Leakage

### ISSUE THREAD

**Issue by PaimonIsSus** [FelixAllard/SCP1507LC#1]
during a run in a modded interior, our frames dipped to 1fps. The flamingos spontaneously multiplied all at once.

**Comment by FelixAllard** [comment]
Sorry I didn't see this thread, I was quite busy, It is hard for me to know exacly what happened with just that sadly. My guess is that you got super unlucky and the number generator fell on 1 multiple time in a row leading to a sudden spawn of millions of flamingo. Which would be more than surprising.
